# Site settings
title: FICAM Playbook
name: FICAM Playbook
email: lachelle.levan@gsa.gov
author:
    name: FICAM
description: Privileged User Guidance
baseurl: '/playbook-privilege'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: pygments

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 
logoalt: Federal Identity Credential and Access Management

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: playbook-privilege
  description: FICAM Playbook - Privileged User Guidance
  url: https://github.com/allietbo/playbook-privilege

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Privileged User Guides Introduction
  url: index.html
  internal: true
  coll: false
- text: Privileged User Guide 1
  url: privilege1
  internal: true
  coll: false
- text: Privileged User Guide 2
  url: privilege2
  internal: true
  coll: false


include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
