# Site settings
title: FICAM Playbook
name: FICAM Playbook
email: lachelle.levan@gsa.gov
author:
    name: FICAM
description: The FICAM Playbook and Guidance materials
baseurl: '/ficam-playbook'
#url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  lachellel
highlighter: pygments

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: 
logoalt: Federal Identity Credential and Access Management

# Repo list
# List repos that you would like to appear on the homepage here
repos:
- name: ficam-playbook
  description: FICAM Playbook & Guidance documents
  url: https://github.com/allietbo/ficam-playbook

# Build settings
markdown: kramdown

exclude:
- bin
- config.rb
- Gemfile
- Gemfile.lock
- gems
- Procfile
- Rakefile
- README.md
- script
- vendor

navigation:
- text: Introduction
  url: index.html
  internal: true
  coll: false
- text: Overview
  url: overview
  internal: true
  coll: false
- text: Privileged Users Guidance
  url: privilege/index/
  internal: true
  coll: true
  collname: privilege
#- text: Applications Diagrams
#  url: applications
#  internal: true
#  coll: false
#- text: Demos
#  url: demos/index/
#  internal: true
#  coll: true
#  collname: usecases
#https://github.com/jekyll/jekyll/issues/2346
#- text: FAQ
#  url: faq
#  internal: true
#  coll: false
- text: Contribute
  url: contribute
  internal: true
  coll: false

#https://github.com/jekyll/jekyll/issues/2346
collections:
  privilege:
    label: "Privileged Users Guidance"
    permalink: privilege/:path/
    output: true
  demos:
    label: "Demos"
    permalink: demos/:path/
    output: true

#- text: Update the config file
#  url: update-the-config-file/
#  internal: true
#  children:
#  - text: Understanding the `baseurl:` property
#    url: understanding-baseurl/
#    internal: true

include:
- _stylesheets
- _javascript



# Custom site configuration
lang: en
